name: Deploy to Firebase Hosting on PR merge

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: |
          firebase logout --force
          firebase login:ci --token "$FIREBASE_TOKEN"
          firebase deploy --only hosting --project ErenYamicQuiz3
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

